### ISSUE TITLE
IMAP to work

### ISSUE THREAD

**Issue by ipflowss** [sdelafond/docker-protonmail-bridge#8] opened 2021-06-27 19:29 UTC
Hi there - I installed protonmail-bridge_1.8.7-1_amd64.deb on ubuntu 20.04 server. But I note an error when adding an account:

```
add
Username:
Password:
Authenticating ...
Two factor code:
Adding account ...
ERRO[Jun 26 13:45:16.907] Could not unmarshal secret error="backend/credentials: malformed secret: malformed credentials" pkg=credentials user=""
Account was added successfully.
```

I can see that my outbound mail is sent without error but fetching mail via IMAP is failing both with freescout and fetchmail.

On the client side I tried the follow options: no encryption/SSL/TLS, SSL, or TLS. Also I turn on and turn off "Validate Certificate" for each of the aformentioned encryption options.

Here is the error from the bridge when IMAP fails

```imap_open(): Couldn't open stream {127.0.0.1:1143/imap/novalidate-cert}. TLS/SSL failure for 127.0.0.1: SSL negotiation failed```

The bridge logs show:

```
ERRO[Jun 26 21:06:56.006] cannot read command: read tcp 127.0.0.1:1143->127.0.0.1:38408: read: connection reset by peer protocol=IMAP
ERRO[Jun 26 21:06:56.007] cannot upgrade connection: EOF protocol=IMAP
ERRO[Jun 26 21:07:06.487] cannot read command: read tcp 127.0.0.1:1143->127.0.0.1:38420: read: connection reset by peer protocol=IMAP
ERRO[Jun 26 21:07:06.488] cannot upgrade connection: EOF protocol=IMAP
ERRO[Jun 26 21:07:06.561] cannot upgrade connection: EOF protocol=IMAP
ERRO[Jun 26 21:07:12.455] cannot read command: read tcp 127.0.0.1:1143->127.0.0.1:38426: read: connection reset by peer protocol=IMAP
ERRO[Jun 26 21:07:12.457] cannot upgrade connection: EOF protocol=IMAP
```

Not sure what else to try.

Cheers

**Comment by sdelafond** [comment] 2021-06-28 06:20
Checking opened issues would have avoided duplicating #7.

**Comment by sdelafond** [comment] 2021-10-29 16:47
Duplicate of #7.

**Closed as completed by sdelafond** 2021-10-29 16:47 UTC
